### ISSUE TITLE
ok_V5 websocket 获取仓位异常

### ISSUE THREAD

**Issue by rzyaly** [zhenpingfeng/exrs#1]
看了下应该是事件枚举转型异常 WebsocketEvent 。希望大佬能修复下。

**Comment by zhenpingfeng** [comment]
应该是你服务器延迟导致的，在还没有登陆成功时就发送了订阅position的请求。加了个sleep应该可以解决。https://github.com/zhenpingfeng/burgerflipper/commit/8f2fcf46be8e441174f5131c536407f409722405
